services:
  db:
    container_name: sdu-db
    extends:
      file: docker-compose.base.yml
      service: db_base

  sdu:
    container_name: sdu-admin
    extends:
      file: docker-compose.base.yml
      service: sdu_dev_base
    depends_on:
      - db

networks:
  internal:
    driver: bridge

volumes:
  sdu_psql:
    name: sdu-pgdata
